<a href="https://colab.research.google.com/github/Ayushibansal805/ML_Datasets/blob/main/f1_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("/content/f1_strategy_dataset_v4.csv")
df

,Driver,LapNumber,Compound,Stint,TyreLife,Position,LapTime (s),Race,Year,LapTime_Delta,Cumulative_Degradation,PitStop,PitNextLap,RaceProgress,Normalized_TyreLife,Position_Change
0,ALB,1,MEDIUM,1,2.0,17,100.625,Abu Dhabi Grand Prix,2023,0.000,0.000,0,0,0.017241,0.117647,0.0
1,ALB,2,MEDIUM,1,3.0,18,93.560,Abu Dhabi Grand Prix,2023,-7.065,-7.065,0,0,0.034483,0.176471,-1.0
2,ALB,3,MEDIUM,1,4.0,18,91.768,Abu Dhabi Grand Prix,2023,-1.792,-8.857,0,0,0.051724,0.235294,0.0
3,ALB,4,MEDIUM,1,5.0,18,91.591,Abu Dhabi Grand Prix,2023,-0.177,-9.034,0,0,0.068966,0.294118,0.0
4,ALB,5,MEDIUM,1,6.0,18,91.422,Abu Dhabi Grand Prix,2023,-0.169,-9.203,0,0,0.086207,0.352941,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101366,ZHO,52,HARD,3,29.0,12,103.373,United States Grand Prix,2022,26.850,-90.264,0,0,0.722222,0.852941,2.0
101367,ZHO,53,HARD,3,30.0,13,105.200,United States Grand Prix,2022,27.061,-88.437,0,0,0.736111,0.882353,1.0
101368,ZHO,54,HARD,3,31.0,13,104.102,United States Grand Prix,2022,27.149,-89.535,0,0,0.750000,0.911765,0.0
101369,ZHO,55,HARD,3,32.0,14,103.812,United States Grand Prix,2022,4.428,-89.825,0,0,0.763889,0.941176,-1.0
101370,ZHO,56,HARD,3,33.0,14,103.881,United States Grand Prix,2022,21.390,-89.756,0,1,0.777778,0.970588,4.0

In [ ]:
df.shape

(101371, 16)

In [ ]:
df.describe()

,LapNumber,Stint,TyreLife,Position,LapTime (s),Year,LapTime_Delta,Cumulative_Degradation,PitStop,PitNextLap,RaceProgress,Normalized_TyreLife,Position_Change
count,101371.000000,101371.000000,101371.000000,101371.000000,101371.000000,101371.000000,101371.000000,101371.000000,101371.000000,101371.000000,101371.000000,101371.000000,101371.000000
mean,30.444841,2.046394,14.549339,9.759132,92.587188,2023.589685,-0.203891,-29.550051,0.251581,0.254797,0.432618,0.386521,-0.004636
std,18.146942,0.948797,10.313385,5.406456,33.231414,1.098518,45.344910,70.235759,0.433924,0.435749,0.258129,0.259906,3.912725
min,1.000000,1.000000,1.000000,1.000000,67.012000,2022.000000,-2403.895000,-274.564000,0.000000,0.000000,0.012821,0.012821,-18.000000
25%,15.000000,1.000000,7.000000,5.000000,82.021000,2023.000000,-7.253000,-51.054500,0.000000,0.000000,0.210526,0.172414,-2.000000
50%,30.000000,2.000000,13.000000,10.000000,91.167000,2024.000000,-0.027000,-21.678000,0.000000,0.000000,0.421053,0.333333,0.000000
75%,45.000000,3.000000,20.000000,14.000000,99.356000,2025.000000,5.705000,-3.725500,1.000000,1.000000,0.631579,0.562500,2.000000
max,78.000000,8.000000,78.000000,20.000000,2526.253000,2025.000000,2433.472000,2412.431000,1.000000,1.000000,1.000000,1.000000,18.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101371 entries, 0 to 101370
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Driver                  101371 non-null  object
 1   LapNumber               101371 non-null  int64
 2   Compound                101305 non-null  object
 3   Stint                   101371 non-null  int64
 4   TyreLife                101371 non-null  float64
 5   Position                101371 non-null  int64
 6   LapTime (s)             101371 non-null  float64
 7   Race                    101371 non-null  object
 8   Year                    101371 non-null  int64
 9   LapTime_Delta           101371 non-null  float64
 10  Cumulative_Degradation  101371 non-null  float64
 11  PitStop                 101371 non-null  int64
 12  PitNextLap              101371 non-null  int64
 13  RaceProgress            101371 non-null  float64
 14  Normalized_TyreLife     101371 non-null  float64
 15  Position_Change         101371 non-null  float64
dtypes: float64(7), int64(6), object(3)
memory usage: 12.4+ MB

In [ ]:
df.isnull().sum()

Driver                     0
LapNumber                  0
Compound                  66
Stint                      0
TyreLife                   0
Position                   0
LapTime (s)                0
Race                       0
Year                       0
LapTime_Delta              0
Cumulative_Degradation     0
PitStop                    0
PitNextLap                 0
RaceProgress               0
Normalized_TyreLife        0
Position_Change            0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

Driver                    0
LapNumber                 0
Compound                  0
Stint                     0
TyreLife                  0
Position                  0
LapTime (s)               0
Race                      0
Year                      0
LapTime_Delta             0
Cumulative_Degradation    0
PitStop                   0
PitNextLap                0
RaceProgress              0
Normalized_TyreLife       0
Position_Change           0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Driver'] = le.fit_transform(df['Driver'])

In [ ]:
df['Compound'] = le.fit_transform(df['Compound'])

In [ ]:
df['Race'] = le.fit_transform(df['Race'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 101305 entries, 0 to 101370
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Driver                  101305 non-null  int64
 1   LapNumber               101305 non-null  int64
 2   Compound                101305 non-null  int64
 3   Stint                   101305 non-null  int64
 4   TyreLife                101305 non-null  float64
 5   Position                101305 non-null  int64
 6   LapTime (s)             101305 non-null  float64
 7   Race                    101305 non-null  int64
 8   Year                    101305 non-null  int64
 9   LapTime_Delta           101305 non-null  float64
 10  Cumulative_Degradation  101305 non-null  float64
 11  PitStop                 101305 non-null  int64
 12  PitNextLap              101305 non-null  int64
 13  RaceProgress            101305 non-null  float64
 14  Normalized_TyreLife     101305 non-null  float64
 15  Position_Change         101305 non-null  float64
dtypes: float64(7), int64(9)
memory usage: 13.1 MB

In [ ]:
y = df['Compound']
x = df.drop('Compound', axis=1)

In [ ]:
 from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=15)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
modelLR = LogisticRegression()

In [ ]:
modelLR.fit(x_train, y_train)
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
y_predLR = modelLR.predict(x_test)
print(accuracy_score(y_test, y_predLR))
print(confusion_matrix(y_test, y_predLR))
print(f1_score(y_test, y_predLR, average='weighted'))

0.5285030353881842
[[6578    1 2449    0    0]
 [ 577    3  507    0    0]
 [3343    4 4123    0    0]
 [1432    0 1157    4    0]
 [  14    0   69    0    0]]
0.4729324330578709

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
modelRF = RandomForestClassifier()
modelRF.fit(x_train, y_train)
y_predRF = modelRF.predict(x_test)
print(accuracy_score(y_test, y_predRF))
print(f1_score(y_test, y_predRF, average='weighted'))

0.9653521543852722
0.9652853445739858

In [ ]:
modelXG = XGBClassifier()
modelXG.fit(x_train, y_train)
y_predXG = modelXG.predict(x_test)
print(accuracy_score(y_test, y_predXG))
print(f1_score(y_test, y_predXG, average='weighted'))

0.918908247371798
0.9186174779208961

In [ ]:
print(y.value_counts())

Compound
0    44967
2    37639
3    12744
1     5556
4      399
Name: count, dtype: int64

In [ ]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_train, Y_train = smote.fit_resample(x_train, y_train)

In [ ]:
modelLR = LogisticRegression()
modelLR.fit(X_train, Y_train)
y_predLR = modelLR.predict(x_test)
print(accuracy_score(y_test, y_predLR))
print(confusion_matrix(y_test, y_predLR))
print(f1_score(y_test, y_predLR, average='weighted'))

0.3355708010463452
[[3606 1599 1284 1763  776]
 [ 218  268  168  159  274]
 [1513  935 2182 1215 1625]
 [ 456  427  542  681  487]
 [   0    0    9   12   62]]
0.38882794169616613

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
modelRF = RandomForestClassifier()
modelRF.fit(X_train, Y_train)
y_predRF = modelRF.predict(x_test)
print(accuracy_score(y_test, y_predRF))
print(f1_score(y_test, y_predRF, average='weighted'))

0.9677705937515424
0.9677614364907122

In [ ]:
modelXG = XGBClassifier()
modelXG.fit(X_train, Y_train)
y_predXG = modelXG.predict(x_test)
print(accuracy_score(y_test, y_predXG))
print(f1_score(y_test, y_predXG, average='weighted'))

0.9094319135284537
0.90927280613411

In [ ]:
from sklearn.svm import SVC #without smote
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_sc = scaler.fit_transform(x_train)
x_test_sc = scaler.transform(x_test)
modelSVC = SVC()
modelSVC.fit(x_train_sc, y_train)
y_predSVC = modelSVC.predict(x_test_sc)

In [ ]:
acc_SVM = accuracy_score(y_test, y_predSVC)
print(acc_SVM)
print(f1_score(y_test, y_predSVC, average='weighted'))

0.7461625783524999
0.7390023204462134

In [ ]:
from sklearn.svm import SVC #with smote
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_sc = scaler.fit_transform(X_train)
x_test_sc = scaler.transform(x_test)
modelSVC = SVC()
modelSVC.fit(x_train_sc, Y_train)
y_predSVC = modelSVC.predict(x_test_sc)

In [ ]:
acc_SVM = accuracy_score(y_test, y_predSVC)
print(acc_SVM)
print(f1_score(y_test, y_predSVC, average='weighted'))

0.7950832188120324
0.7969531773594147